name: Daily Weekday Broker Stock Report

on:
  schedule:
    # 4:00 AM UTC converts exactly to 9:30 AM IST
    # '1-5' restricts the execution strictly to Monday through Friday
    - cron: '0 4 * * 1-5'
  workflow_dispatch: # Keeps the manual play button active
env:
 # FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      # Updated from v4.2.0 to v4.2.2
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # Updated from v5.2.0 to v5.3.0
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pandas yagmail beautifulsoup4 lxml requests

      - name: Run Script
        run: python stock_reporter.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

